version: '3.7'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:ro
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro


  wp:
    image: wordpress:latest # https://hub.docker.com/_/wordpress/
    restart: always
    expose:
      - "80" # change ip if required
    volumes:
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./wp-app:/var/www/html # Full wordpress project
      - ./plugin-name/trunk/:/var/www/html/wp-content/plugins/plugin-name # Plugin development
      - ./theme-name/trunk/:/var/www/html/wp-content/themes/theme-name # Theme development
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: "${DB_NAME}"
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "${DB_ROOT_PASSWORD}"
      VIRTUAL_HOST: sdprueba.lolguin.info,www.sdprueba.lolguin.info
      LETSENCRYPT_HOST: sdprueba.lolguin.info,www.sdprueba.lolguin.info
      LETSENCRYPT_EMAIL: lujeolhe@gmail.com
    depends_on:
      - db
      - nginx-proxy
      - letsencrypt  

 
  wpcli:
    image: wordpress:cli
    volumes:
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./wp-app:/var/www/html
    depends_on:
      - db
      - wp

  db:
    image: mysql:latest # https://hub.docker.com/_/mysql/ - or mariadb https://hub.docker.com/_/mariadb
    ports:
      - ${IP}:3306:3306 # change ip if required
    command: [
        '--default_authentication_plugin=mysql_native_password',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
    ]
    volumes:
      - ./wp-data:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      #######################################Segundo WP#####################################

 
  wp2:
    image: wordpress:latest # https://hub.docker.com/_/wordpress/
    restart: always
    expose:
      - "80" # change ip if required
    volumes:
      - ./config2/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./wp-app2:/var/www/html # Full wordpress project
      - ./plugin-name2/trunk/:/var/www/html/wp-content/plugins/plugin-name # Plugin development
      - ./theme-name2/trunk/:/var/www/html/wp-content/themes/theme-name # Theme development
    environment:
      WORDPRESS_DB_HOST: db2
      WORDPRESS_DB_NAME: "${DB_NAME2}"
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "${DB_ROOT_PASSWORD2}"
      VIRTUAL_HOST: sdprueba2.lolguin.info,www.sdprueba2.lolguin.info
      LETSENCRYPT_HOST: sdprueba2.lolguin.info,www.sdprueba2.lolguin.info
      LETSENCRYPT_EMAIL: lujeolhe@gmail.com
    depends_on:
      - db2
      - nginx-proxy
      - letsencrypt  

 
  wpcli2:
    image: wordpress:cli
    volumes:
      - ./config2/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./wp-app2:/var/www/html
    depends_on:
      - db2
      - wp2

  db2:
    image: mysql:latest # https://hub.docker.com/_/mysql/ - or mariadb https://hub.docker.com/_/mariadb
    ports:
      - ${IP}:3307:3307 # change ip if required
    command: [
        '--default_authentication_plugin=mysql_native_password',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
    ]
    volumes:
      - ./wp-data2:/docker-entrypoint-initdb.d
      - db_data2:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "${DB_NAME2}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD2}"
     
volumes:
  db_data: 
  db_data2: 
  certs:
  html:
  vhostd:
